import type { SxProps, Theme } from '@mui/material/styles'

// About-specific composition; shared colors and typography live in theme.ts.
export const aboutStyles = {
  hero: { py: { xs: 3, md: 7 } },
  greeting: { color: 'portfolio.greeting', mb: 1.5 },
  introduction: { maxWidth: 590 },
  portrait: {
    position: 'relative',
    bgcolor: 'portfolio.portrait',
    border: 1,
    borderColor: 'portfolio.portraitBorder',
    borderRadius: '120px 120px 24px 24px',
    px: 3,
    py: 5,
    maxWidth: 340,
    mx: 'auto',
    overflow: 'hidden',
  },
  decoration: {
    position: 'absolute',
    width: 280,
    height: 280,
    border: 1,
    borderColor: 'portfolio.decorationBorder',
    borderRadius: '50%',
    top: -80,
    right: -110,
  },
  avatar: {
    width: { xs: 180, sm: 210 },
    height: { xs: 180, sm: 210 },
    mx: 'auto',
    bgcolor: 'portfolio.avatar',
    color: 'primary.main',
    fontSize: '4rem',
    fontWeight: 500,
    border: '8px solid',
    borderColor: 'portfolio.avatarBorder',
    position: 'relative',
  },
  name: { textAlign: 'center', mt: 3, color: 'portfolio.name' },
  role: { textAlign: 'center', mt: 0.5, color: 'portfolio.role' },
  highlights: { mt: 2, mb: 5 },
  contactPanel: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'minmax(0, 1fr) 220px' },
    alignItems: 'center',
    gap: { xs: 3, md: 6 },
    p: { xs: 3, sm: 4, md: 5 },
    mt: { xs: 6, md: 8 },
    mb: 3,
    bgcolor: 'primary.light',
    borderColor: 'portfolio.portraitBorder',
  },
  contactContent: {
    display: 'flex',
    flexDirection: { xs: 'column', sm: 'row' },
    alignItems: 'flex-start',
    gap: 2.5,
  },
  contactIcon: {
    display: 'grid',
    placeItems: 'center',
    width: 52,
    height: 52,
    flexShrink: 0,
    borderRadius: 3,
    bgcolor: 'background.default',
    color: 'primary.main',
    fontSize: '1.4rem',
  },
  contactActions: { minWidth: 0 },
  contactLink: {
    minHeight: 46,
    px: 2.5,
    flex: { sm: 1, md: 'initial' },
    justifyContent: 'space-between',
    gap: 2,
    borderRadius: 2,
    textTransform: 'none',
    fontWeight: 600,
    '&:focus-visible': {
      outline: '2px solid',
      outlineColor: 'primary.main',
      outlineOffset: 3,
    },
  },
  experience: { mt: { xs: 6, md: 8 }, mb: 5 },
  education: { mt: { xs: 6, md: 8 }, mb: 5 },
  educationCard: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '210px minmax(0, 1fr)' },
    gap: { xs: 3, md: 4 },
    p: { xs: 2.5, sm: 4 },
    borderTop: '3px solid',
    borderTopColor: 'secondary.main',
  },
  educationMeta: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 0.5,
  },
  educationIcon: {
    display: 'grid',
    placeItems: 'center',
    width: 48,
    height: 48,
    borderRadius: 3,
    bgcolor: 'primary.light',
    color: 'primary.main',
    fontSize: '1.4rem',
    mb: 1.5,
  },
  educationContent: {
    minWidth: 0,
    alignSelf: 'center',
    borderColor: 'divider',
    borderTop: { xs: 1, md: 0 },
    borderLeft: { xs: 0, md: 1 },
    pt: { xs: 3, md: 0 },
    pl: { xs: 0, md: 4 },
    py: { md: 1 },
  },
  experienceCard: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '210px minmax(0, 1fr)' },
    gap: { xs: 3, md: 4 },
    p: { xs: 2.5, sm: 4 },
    borderTop: '3px solid',
    borderTopColor: 'secondary.main',
  },
  experienceMeta: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0.5,
  },
  experienceContributions: {
    pl: 2.5,
    my: 2,
    color: 'text.secondary',
    '& li': { pl: 0.5, mb: 1.25 },
    '& li::marker': { color: 'primary.main' },
  },
  experienceDetails: {
    '& summary': {
      cursor: 'pointer',
      color: 'primary.main',
      fontWeight: 600,
      fontSize: '0.9rem',
      borderRadius: 1,
      py: 0.5,
      '&:hover': { textDecoration: 'underline' },
      '&:focus-visible': { outline: '2px solid', outlineOffset: 4 },
    },
  },
  highlightPanel: { height: '100%', p: { xs: 3, sm: 3.5 } },
  accent: {
    width: 28,
    height: 4,
    borderRadius: 2,
    bgcolor: 'secondary.main',
    mb: 2.5,
  },
  highlightHeading: { color: 'portfolio.highlightHeading', mb: 1 },
  skillGroupHeading: { color: 'text.primary', mb: 1.5 },
  skillPanel: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
    height: '100%',
    p: 1.5,
  },
  skillImage: { width: 28, height: 28, objectFit: 'contain', flexShrink: 0 },
} satisfies Record<string, SxProps<Theme>>
